# Generated by Django 4.1.1 on 2022-10-01 16:41

import Issues.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(default=Issues.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('issue_status', models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('DONOR', 'DONOR'), ('NGO', 'NGO')], default='DONOR', max_length=30, verbose_name='User Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
