# Generated by Django 4.1.1 on 2022-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(default='issue', max_length=100),
            preserve_default=False,
        ),
    ]
