# Generated by Django 4.1.1 on 2022-10-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRequest', '0005_alter_request_address'),
        ('Issues', '0002_issue_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='request',
            field=models.ForeignKey(default='req id', on_delete=django.db.models.deletion.CASCADE, to='FoodRequest.request'),
            preserve_default=False,
        ),
    ]
