# Generated by Django 4.1.1 on 2022-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=36),
        ),
    ]
