# Generated by Django 4.1.1 on 2022-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRequest', '0003_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='company_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('EVENTS', 'EVENTS'), ('COLLEGE', 'COLLEGE'), ('OTHERS', 'OTHERS')], default='vamsi', max_length=30),
            preserve_default=False,
        ),
    ]
