# Generated by Django 4.1.1 on 2022-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRequest', '0006_alter_request_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
