# Generated by Django 4.1.1 on 2022-11-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodRequest', '0007_request_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'NGO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
    ]
