# Generated by Django 4.1.1 on 2022-11-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRequest', '0008_alter_request_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
