# Generated by Django 4.1.1 on 2022-09-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='city',
            field=models.CharField(choices=[('NEW_YORK', 'NEW_YORK'), ('LOS_ANGELES', 'LOS_ANGELES'), ('WASHINGTON', 'WASHINGTON')], default='WASHINGTON', max_length=30, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='user_type',
            field=models.CharField(choices=[('DONOR', 'DONOR'), ('NGO', 'NGO')], default='DONOR', max_length=30, verbose_name='User Type'),
        ),
    ]
