# Generated by Django 4.1.1 on 2022-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailuser_city_emailuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Manchester', 'Manchester'), ('Bristol', 'Bristol'), ('Leicester', 'Leicester')], default='Leicester', max_length=30, verbose_name='City'),
        ),
    ]
