# Generated by Django 4.0.5 on 2022-08-07 16:07

import Address.models
import Address.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=Address.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[Address.validations.validate_phone], verbose_name='Phone Number')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('address_line', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address Line')),
                ('extend_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Extend Address')),
                ('landmark', models.CharField(blank=True, max_length=250, null=True, verbose_name='Landmark')),
                ('city', models.CharField(choices=[('Visakhapatnam', 'Visakhapatnam'), ('Hyderabad', 'Hyderabad'), ('Vijayawada', 'Vijayawada'), ('Bangalore', 'Bangalore'), ('Hubli', 'Hubli'), ('Gokarna', 'Gokarna'), ('Dandali', 'Dandali'), ('Hampi', 'Hampi'), ('Mysore', 'Mysore'), ('Coorg', 'Coorg'), ('Chikmagalur', 'Chikmagalur'), ('Tambaram', 'Tambaram'), ('Pondicherry', 'Pondicherry'), ('Ooty', 'Ooty'), ('Coonoor', 'Coonoor'), ('Coimbatore', 'Coimbatore'), ('Kodaikanal', 'Kodaikanal'), ('Delhi', 'Delhi'), ('Manali', 'Manali'), ('Agra', 'Agra')], default='Visakhapatnam', max_length=30, verbose_name='City')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu And Kashmir', 'Jammu And Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman And Nicobar', 'Andaman And Nicobar'), ('Chandigarh', 'Chandigarh'), ('Dadra And Nagar Haveli', 'Dadra And Nagar Haveli'), ('Daman And Diu', 'Daman And Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], default='Andhra Pradesh', max_length=30, verbose_name='State')),
                ('country', models.CharField(choices=[('INDIA', 'INDIA')], default='INDIA', max_length=30, verbose_name='Country')),
                ('latitude', models.CharField(blank=True, max_length=15, null=True, validators=[Address.validations.validate_latitude], verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=15, null=True, validators=[Address.validations.validate_longitude], verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK')], default='HOME', max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.address', verbose_name='Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
