# Generated by Django 4.0.3 on 2022-09-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0004_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('NEW YORK', 'NEW YORK')], default='NEW YORK', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('UNITED STATES OF AMERICA', 'UNITED STATES OF AMERICA')], default='UNITED STATES OF AMERICA', max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('CALIFORNIA', 'CALIFORNIA')], default='CALIFORNIA', max_length=30, verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='UserSavedAddress',
        ),
    ]
