# Generated by Django 4.1.1 on 2022-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0005_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('NEW_YORK', 'NEW_YORK'), ('LOS_ANGELES', 'LOS_ANGELES'), ('WASHINGTON', 'WASHINGTON')], default='NEW_YORK', max_length=30, verbose_name='City'),
        ),
    ]
