# Generated by Django 4.1.1 on 2022-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0006_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Manchester', 'Manchester'), ('Bristol', 'Bristol'), ('Leicester', 'Leicester')], default='London', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('United States of America', 'United States of America'), ('United Kingdom', 'United Kingdom'), ('England', 'England')], default='United Kingdom', max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Bedfordshire', 'Bedfordshire'), ('Cornwall', 'Cornwall'), ('Cambridgeshire', 'Cambridgeshire'), ('Le2 1xp', 'Le2 1xp')], default='Cambridgeshire', max_length=30, verbose_name='State'),
        ),
    ]
